/*
 * The MIT License
 *
 * Copyright 2022 Bruno Lucas Alcantara de Oliveira.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package br.com.projeto.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;

/**
 *
 * @author Bruno Oliveira
 * @version 0.1
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public String usuariologado;
    public String usuarioCargo;
    public String lblOperador;
    

    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        telaControleCliente = new javax.swing.JMenuItem();
        telaConsultaCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        telaControleFuncionario = new javax.swing.JMenuItem();
        telaControleFuncionarios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        telaControleFornecedor = new javax.swing.JMenuItem();
        telaConsultaFornecedores = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        telaControledeEstoque = new javax.swing.JMenuItem();
        telaConsultaProdutos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        telaAbrirPDV = new javax.swing.JMenuItem();
        telaPosicaoDia = new javax.swing.JMenuItem();
        telaHistoricoVendas = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        telaTrocarUsuario = new javax.swing.JMenuItem();
        SairPrograma = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de controle de estoque");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Usuário logado:");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 204));
        lblUsuario.setText("Bruno");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cargo:");

        lblCargo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(0, 0, 204));
        lblCargo.setText("Bruno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario)
                .addGap(192, 192, 192)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCargo)
                .addContainerGap(432, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUsuario)
                    .addComponent(jLabel2)
                    .addComponent(lblCargo))
                .addContainerGap())
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/clientes.png"))); // NOI18N
        jMenu1.setText("Clientes");

        telaControleCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/clientes.png"))); // NOI18N
        telaControleCliente.setText("Controle de clientes");
        telaControleCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaControleClienteActionPerformed(evt);
            }
        });
        jMenu1.add(telaControleCliente);

        telaConsultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/clientes.png"))); // NOI18N
        telaConsultaCliente.setText("Consulta de clientes");
        telaConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaConsultaClienteActionPerformed(evt);
            }
        });
        jMenu1.add(telaConsultaCliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/funcionarios.png"))); // NOI18N
        jMenu2.setText("Funcionários");

        telaControleFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/funcionarios.png"))); // NOI18N
        telaControleFuncionario.setText("Controle de funcionários");
        telaControleFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaControleFuncionarioActionPerformed(evt);
            }
        });
        jMenu2.add(telaControleFuncionario);

        telaControleFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/funcionarios.png"))); // NOI18N
        telaControleFuncionarios.setText("Consulta de funcionários");
        telaControleFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaControleFuncionariosActionPerformed(evt);
            }
        });
        jMenu2.add(telaControleFuncionarios);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/fornecedores.png"))); // NOI18N
        jMenu3.setText("Fornecedores");

        telaControleFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/fornecedores.png"))); // NOI18N
        telaControleFornecedor.setText("Controle de fornecedores");
        telaControleFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaControleFornecedorActionPerformed(evt);
            }
        });
        jMenu3.add(telaControleFornecedor);

        telaConsultaFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/fornecedores.png"))); // NOI18N
        telaConsultaFornecedores.setText("Consulta de fornecedores");
        telaConsultaFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaConsultaFornecedoresActionPerformed(evt);
            }
        });
        jMenu3.add(telaConsultaFornecedores);

        jMenuBar1.add(jMenu3);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/produtos.png"))); // NOI18N
        jMenu6.setText("Produtos");

        telaControledeEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/produtos.png"))); // NOI18N
        telaControledeEstoque.setText("Controle de estoque");
        telaControledeEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaControledeEstoqueActionPerformed(evt);
            }
        });
        jMenu6.add(telaControledeEstoque);

        telaConsultaProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/produtos.png"))); // NOI18N
        telaConsultaProdutos.setText("Consulta de produtos");
        telaConsultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaConsultaProdutosActionPerformed(evt);
            }
        });
        jMenu6.add(telaConsultaProdutos);

        jMenuBar1.add(jMenu6);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/vendas.png"))); // NOI18N
        jMenu4.setText("Vendas");

        telaAbrirPDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/vendas.png"))); // NOI18N
        telaAbrirPDV.setText("Abrir PDV");
        telaAbrirPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaAbrirPDVActionPerformed(evt);
            }
        });
        jMenu4.add(telaAbrirPDV);

        telaPosicaoDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/vendas.png"))); // NOI18N
        telaPosicaoDia.setText("Posição do dia");
        telaPosicaoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaPosicaoDiaActionPerformed(evt);
            }
        });
        jMenu4.add(telaPosicaoDia);

        telaHistoricoVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/vendas.png"))); // NOI18N
        telaHistoricoVendas.setText("Histórico de vendas");
        telaHistoricoVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaHistoricoVendasActionPerformed(evt);
            }
        });
        jMenu4.add(telaHistoricoVendas);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/configuracoes.png"))); // NOI18N
        jMenu5.setText("Configurações");

        telaTrocarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/configuracoes.png"))); // NOI18N
        telaTrocarUsuario.setText("Trocar de usuário");
        telaTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaTrocarUsuarioActionPerformed(evt);
            }
        });
        jMenu5.add(telaTrocarUsuario);

        jMenuBar1.add(jMenu5);

        SairPrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pacotes icones/sair.png"))); // NOI18N
        SairPrograma.setText("Sair");
        SairPrograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairProgramaMouseClicked(evt);
            }
        });
        jMenuBar1.add(SairPrograma);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 216, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Forms do menu abrir maximizado
        this.setExtendedState(this.MAXIMIZED_BOTH);
        //Mostrar qual usuario está logado
        lblUsuario.setText(usuariologado);
        //Mostrar cargo do usuario.
        lblCargo.setText(usuarioCargo);
        this.setVisible(true);
    }//GEN-LAST:event_formWindowActivated

    private void telaControleFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaControleFornecedorActionPerformed
        // Botão para acessar a tela de fornecedor
        frmFornecedor telaControleFornecedor = new frmFornecedor();
        telaControleFornecedor.setVisible(true);

    }//GEN-LAST:event_telaControleFornecedorActionPerformed

    private void telaControleFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaControleFuncionarioActionPerformed
        // Botão para acessar a tela de funcionario
        frmFuncionario telaControleFuncionario = new frmFuncionario();
        telaControleFuncionario.setVisible(true);
    }//GEN-LAST:event_telaControleFuncionarioActionPerformed

    private void telaControleClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaControleClienteActionPerformed
        // Botão para acessar a tela de cliente
        frmCliente telaControleCliente = new frmCliente();
        telaControleCliente.setVisible(true);
    }//GEN-LAST:event_telaControleClienteActionPerformed

    private void telaTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaTrocarUsuarioActionPerformed
        // Botão trocar de usuário, efetuar logout
        frmLogin telaLogin = new frmLogin();
        int retorno;

        retorno = JOptionPane.showConfirmDialog(null, "Desejar trocar de usuário?");

        //Condição para caso usuário não desejar trocar o usuário.
        if (retorno == 0) {
            this.dispose();
            telaLogin.setVisible(true);
        }


    }//GEN-LAST:event_telaTrocarUsuarioActionPerformed

    private void SairProgramaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairProgramaMouseClicked
        // Ao clicar com mouse, com uma pergunta
        int retorno;

        retorno = JOptionPane.showConfirmDialog(null, "Desejar sair?");

        //Condição para quando usuário clicar "Sim" a aplicação encerrar.
        if (retorno == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_SairProgramaMouseClicked

    private void telaConsultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaConsultaProdutosActionPerformed
        // Botão consultar produto
        frmProduto tela = new frmProduto();
        //Selecionar a tela de consulta, chamando pela guia.
        tela.jTabbedPane1.setSelectedIndex(1);
        tela.setVisible(true);
    }//GEN-LAST:event_telaConsultaProdutosActionPerformed

    private void telaAbrirPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaAbrirPDVActionPerformed
        // Botão abrir pdv
        frmVendas telaPDV = new frmVendas();
        
        telaPDV.usuariologado = getString("nome");
        telaPDV.setVisible(true);
        

    }//GEN-LAST:event_telaAbrirPDVActionPerformed

    private void telaPosicaoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaPosicaoDiaActionPerformed
        // Botão posição do dia
        frmTotalVenda telaPosicaoDia = new frmTotalVenda();
        telaPosicaoDia.setVisible(true);
    }//GEN-LAST:event_telaPosicaoDiaActionPerformed

    private void telaHistoricoVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaHistoricoVendasActionPerformed
        // Botão Controle de vendas
        frmHistorico telaHistorico = new frmHistorico();
        telaHistorico.setVisible(true);
    }//GEN-LAST:event_telaHistoricoVendasActionPerformed

    private void telaControleFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaControleFuncionariosActionPerformed
        // Botão consultar funcionarios
        frmFuncionario tela = new frmFuncionario();
        //Selecionar a tela de consulta, chamando pela guia.
        tela.jTabbedPane1.setSelectedIndex(1);
        tela.setVisible(true);
    }//GEN-LAST:event_telaControleFuncionariosActionPerformed

    private void telaConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaConsultaClienteActionPerformed
        // Botão consultar cliente
        frmCliente tela = new frmCliente();
        //Selecionar a tela de consulta, chamando pela guia.
        tela.jTabbedPane1.setSelectedIndex(1);
        tela.setVisible(true);
    }//GEN-LAST:event_telaConsultaClienteActionPerformed

    private void telaConsultaFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaConsultaFornecedoresActionPerformed
        // Botão consultar fornecedores
        frmFornecedor tela = new frmFornecedor();
        //Selecionar a tela de consulta, chamando pela guia.
        tela.jTabbedPane1.setSelectedIndex(1);
        tela.setVisible(true);
    }//GEN-LAST:event_telaConsultaFornecedoresActionPerformed

    private void telaControledeEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telaControledeEstoqueActionPerformed
        // Botão controle de estoque
        frmEstoque tela = new frmEstoque();
        tela.setVisible(true);
    }//GEN-LAST:event_telaControledeEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu SairPrograma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCargo;
    public javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem telaAbrirPDV;
    private javax.swing.JMenuItem telaConsultaCliente;
    private javax.swing.JMenuItem telaConsultaFornecedores;
    private javax.swing.JMenuItem telaConsultaProdutos;
    public javax.swing.JMenuItem telaControleCliente;
    public javax.swing.JMenuItem telaControleFornecedor;
    public javax.swing.JMenuItem telaControleFuncionario;
    private javax.swing.JMenuItem telaControleFuncionarios;
    private javax.swing.JMenuItem telaControledeEstoque;
    public javax.swing.JMenuItem telaHistoricoVendas;
    public javax.swing.JMenuItem telaPosicaoDia;
    private javax.swing.JMenuItem telaTrocarUsuario;
    // End of variables declaration//GEN-END:variables
}
